#!/usr/bin/env python3
"""Generate chain-of-thought rationales for dataset records via an LLM API.

Each record's `alt` field is replaced with a reasoning trace that ends with the
target answer (the original value of `alt`). The transformed records are
written incrementally to a JSONL output file so progress is saved even if the
run is interrupted.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional dependency
    load_dotenv = None

try:
    from openai import (
        OpenAI,
        APIConnectionError,
        APIError,
        APIStatusError,
        APITimeoutError,
        RateLimitError,
    )
except ImportError as exc:  # pragma: no cover - signals missing dependency early
    raise SystemExit(
        "The `openai` package is required. Install it via `pip install openai`."
    ) from exc


RetryableError = (
    APIStatusError,
    RateLimitError,
    APITimeoutError,
    APIConnectionError,
    APIError,
    TimeoutError,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replace `alt` with CoT reasoning generated by an LLM."
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Input dataset (JSON array or JSONL).",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output JSONL file with updated records.",
    )
    parser.add_argument(
        "--model",
        default=os.getenv("OPENAI_MODEL", "gpt-4.1"),
        help="Model name to request.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.2,
        help="Sampling temperature.",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=int(os.getenv("REQUEST_MAX_RETRIES", 5)),
        help="Maximum attempts per request.",
    )
    parser.add_argument(
        "--request-timeout",
        type=float,
        default=float(os.getenv("REQUEST_TIMEOUT", 60)),
        help="Timeout in seconds for each request.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from an existing output file by skipping completed lines.",
    )
    parser.add_argument(
        "--retain-original-alt",
        action="store_true",
        help="Keep the original `alt` value in a new `alt_answer` field.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show the constructed prompt for the first record and exit.",
    )
    parser.add_argument(
        "--cot-only",
        action="store_true",
        help="Return only the reasoning text without an explicit 'Answer:' line.",
    )

    env_use_chat = os.getenv("OPENAI_USE_CHAT_COMPLETIONS", "").lower() in {
        "1",
        "true",
        "yes",
    }
    parser.add_argument(
        "--use-chat-completions",
        action="store_true",
        default=env_use_chat,
        dest="use_chat_completions",
        help="Use the Chat Completions endpoint instead of the Responses API.",
    )
    parser.add_argument(
        "--responses-api",
        action="store_false",
        dest="use_chat_completions",
        help="Force usage of the Responses API even if the environment opts in to Chat Completions.",
    )
    return parser.parse_args()


def load_input_records(path: Path) -> List[Dict]:
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")

    if path.suffix.lower() == ".jsonl":
        records: List[Dict] = []
        with path.open("r", encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, 1):
                stripped = line.strip()
                if not stripped:
                    continue
                try:
                    records.append(json.loads(stripped))
                except json.JSONDecodeError as exc:
                    raise ValueError(
                        f"Invalid JSON on line {line_number} of {path}"
                    ) from exc
        return records

    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    if not isinstance(data, list):
        raise ValueError("Expected the input JSON to be an array of objects.")

    return data


def count_completed_lines(path: Path) -> int:
    if not path.exists():
        return 0
    completed = 0
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                completed += 1
    return completed


def create_client() -> OpenAI:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit(
            "OPENAI_API_KEY is not set. Create a `.env` file based on `.env.template`."
        )
    base_url = os.getenv("OPENAI_BASE_URL")
    if base_url:
        return OpenAI(api_key=api_key, base_url=base_url)
    return OpenAI(api_key=api_key)


def extract_text(response: Any) -> str:
    """Best-effort extraction of text content from diverse OpenAI client responses."""
    if response is None:
        raise ValueError("Model returned no response.")

    if isinstance(response, str):
        text = response
    elif hasattr(response, "output_text"):
        text = response.output_text  # type: ignore[attr-defined]
    elif hasattr(response, "output") and isinstance(getattr(response, "output"), list):
        # OpenAI Responses API returns structured content blocks.
        parts: List[str] = []
        for block in response.output:  # type: ignore[attr-defined]
            content = getattr(block, "content", None)
            if isinstance(content, list):
                for chunk in content:
                    chunk_type = getattr(chunk, "type", None)
                    if isinstance(chunk, dict):
                        chunk_type = chunk.get("type")
                        chunk_text = chunk.get("text")
                    else:
                        chunk_text = getattr(chunk, "text", None)
                    if chunk_type in {"output_text", "text", None} and chunk_text:
                        parts.append(str(chunk_text))
            elif isinstance(content, str):
                parts.append(content)
        text = "\n".join(parts)
    elif isinstance(response, dict):
        if "output_text" in response:
            text = response["output_text"]  # type: ignore[assignment]
        elif "choices" in response:
            choices = response["choices"]
            if not choices:
                raise ValueError("Model returned no choices.")
            message = choices[0].get("message")
            if message and "content" in message:
                text = message["content"]
            else:
                text = choices[0].get("text", "")
        else:
            text = str(response)
    elif hasattr(response, "choices"):
        choices = response.choices  # type: ignore[attr-defined]
        if not choices:
            raise ValueError("Model returned no choices.")
        first = choices[0]
        if hasattr(first, "message") and getattr(first.message, "content", None):
            text = first.message.content
        else:
            text = getattr(first, "text", "")
    else:
        text = str(response)

    if not text:
        raise ValueError("Unable to extract non-empty text from model response.")
    return text


def build_prompt(record: Dict, target_answer: str, include_answer_line: bool) -> str:
    subject = record.get("subject", "Unknown subject")
    src = record.get("src") or record.get("question") or "Unknown question"
    rephrase = record.get("rephrase")

    lines: List[str] = [
        "You are given information about an editing example.",
        f"Subject: {subject}",
        f"Original question: {src}",
    ]
    if rephrase:
        lines.append(f"Paraphrased question: {rephrase}")

    if include_answer_line:
        lines.extend(
            [
                "",
                "Task:",
                "1. Reason step-by-step to answer the original question.",
                "2. Ensure every step logically supports the final answer.",
                f"3. This is a knowledge editing scenario: treat {target_answer} as the corrected fact and reinforce it.",
                "4. Each sentence in the reasoning must explicitly justify why the final answer is correct.",
                "5. Do not mention, compare, or speculate about alternative answers or guesses.",
                f"6. The final answer must be exactly: {target_answer}",
                "",
                "Format your response as:",
                "Reasoning: <multi-sentence explanation>",
                f"Answer: {target_answer}",
            ]
        )
    else:
        lines.extend(
            [
                "",
                "Task:",
                "1. Reason step-by-step to answer the original question.",
                "2. Ensure every step logically supports the conclusion.",
                f"3. This is a knowledge editing scenario: treat {target_answer} as the corrected fact and reinforce it.",
                "4. Each sentence in the reasoning must explicitly justify why the final answer is correct.",
                "5. Do not mention, compare, or speculate about alternative answers or guesses.",
                f"6. Conclude with a sentence that states the correct answer: {target_answer}.",
                "",
                "Output only the reasoning paragraphs in English.",
                "Do not add a separate line prefixed with 'Answer:'.",
            ]
        )

    return "\n".join(lines)


def generate_cot(
    client: OpenAI,
    record: Dict,
    *,
    model: str,
    temperature: float,
    timeout: float,
    max_retries: int,
    include_answer_line: bool,
    use_chat_completions: bool,
) -> str:
    target_answer = record.get("alt")
    if not target_answer:
        raise ValueError("Record is missing the `alt` field to serve as target answer.")

    system_prompt = (
        "You are assisting with a knowledge editing task. Produce thorough but concise "
        "chains of thought that reinforce the edited fact and justify the final answer only."
    )
    user_prompt = build_prompt(record, str(target_answer), include_answer_line)

    attempt = 0
    while True:
        attempt += 1
        try:
            if use_chat_completions:
                response = client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=temperature,
                    max_tokens=800,
                    timeout=timeout,
                )
            else:
                response = client.responses.create(
                    model=model,
                    input=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=temperature,
                    max_output_tokens=800,
                    timeout=timeout,
                )
            text = extract_text(response).strip()
            if not text:
                raise ValueError("Model returned empty output.")
            if include_answer_line:
                if f"Answer: {target_answer}" not in text:
                    text = f"{text.rstrip()}\nAnswer: {target_answer}"
            else:
                # Remove any accidental "Answer:" lines the model may include.
                lines = [
                    line
                    for line in text.splitlines()
                    if not line.strip().startswith("Answer:")
                ]
                text = "\n".join(lines).strip()
                if target_answer not in text:
                    text = (
                        f"{text.rstrip()} Therefore, the correct answer is {target_answer}."
                )
            return text
        except RetryableError as exc:
            if attempt >= max_retries:
                raise
            wait_time = min(2 ** attempt, 30)
            print(
                f"Retryable error ({exc.__class__.__name__}): {exc}. "
                f"Retrying in {wait_time} seconds...",
                file=sys.stderr,
            )
            time.sleep(wait_time)


def main() -> None:
    if load_dotenv is not None:
        load_dotenv()
    else:
        print(
            "python-dotenv is not installed; skipping automatic .env loading.",
            file=sys.stderr,
        )
    args = parse_args()

    records = load_input_records(args.input)
    print(f"Loaded {len(records)} records from {args.input}")

    if args.output.exists():
        if not args.resume:
            raise SystemExit(
                f"Output file {args.output} already exists. "
                "Use --resume to append or remove the file first."
            )
        processed = count_completed_lines(args.output)
        mode = "a"
        print(f"Resuming from {processed} completed records.")
    else:
        processed = 0
        mode = "w"

    include_answer_line = not args.cot_only

    if args.dry_run:
        if not records:
            raise SystemExit("No records available for dry run.")
        sample_prompt = build_prompt(
            records[0],
            str(records[0].get("alt")),
            include_answer_line,
        )
        print("=== System Prompt ===")
        print(
            "You are a careful reasoning assistant. Produce thorough but concise "
            "chains of thought that justify the final answer."
        )
        print("=== User Prompt ===")
        print(sample_prompt)
        return

    client = create_client()

    remaining = records[processed:]
    if not remaining:
        print("No new records to process.")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open(mode, encoding="utf-8") as handle:
        for index, record in enumerate(remaining, start=processed):
            original_alt = record.get("alt")
            try:
                cot = generate_cot(
                    client,
                    record,
                    model=args.model,
                    temperature=args.temperature,
                    timeout=args.request_timeout,
                    max_retries=args.max_retries,
                    include_answer_line=include_answer_line,
                    use_chat_completions=args.use_chat_completions,
                )
            except Exception as exc:  # noqa: BLE001 - surfaces fatal errors promptly
                print(
                    f"Failed to generate CoT for record {index}: {exc}",
                    file=sys.stderr,
                )
                raise

            updated_record = dict(record)
            if args.retain_original_alt and original_alt is not None:
                updated_record["alt_answer"] = original_alt
            updated_record["alt"] = cot

            handle.write(json.dumps(updated_record, ensure_ascii=False))
            handle.write("\n")
            handle.flush()
            print(f"Processed record {index + 1}/{len(records)}", end="\r")

    print(f"\nCompleted. Output written to {args.output}")


if __name__ == "__main__":
    main()
